// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  example

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( A ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* A ) UnmarshalJSON([]byte) error { return nil }
func ( A ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* A ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_A *A
